# ???????? ????????
spring.datasource.url=jdbc:postgresql://localhost:5432/schooldb
spring.datasource.username=postgres
spring.datasource.password=896
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.admin.username=admin
app.admin.password=admin123
app.admin.email=admin@example.com

# Mail (SMTP) configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=nurgulaiazkhan@gmail.com
spring.mail.password=rann ydrk bdwf bybn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=nurgulaiazkhan@gmail.com
